// Auto-generated from deryabilardo.com product data
// 151 products across bilardo, dart, and oyun categories

export type Category = 'bilardo' | 'dart' | 'oyun';

export interface Subcategory {
  slug: string;
  name: string;
  category: Category;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  image: string;
  category: Category;
  subcategorySlug: string;
  brand: string | null;
  sourceUrl: string;
}

export const categoryNames: Record<Category, string> = {
  bilardo: 'Bilardo',
  dart: 'Dart',
  oyun: 'Oyun',
};

export const subcategories: Subcategory[] = [
  { slug: "3-bant-bilardo-toplari", name: "3 Bant Bilardo Toplar\u0131", category: "bilardo" },
  { slug: "amerikan-bilardo-toplari", name: "Amerikan Bilardo Toplar\u0131", category: "bilardo" },
  { slug: "bilardo-aksesuarlari", name: "Bilardo Aksesuarlar\u0131", category: "bilardo" },
  { slug: "bilardo-eldivenleri", name: "Bilardo Eldivenleri", category: "bilardo" },
  { slug: "bilardo-istakalari", name: "Bilardo Istakalar\u0131", category: "bilardo" },
  { slug: "bilardo-tebesirleri", name: "Bilardo Tebe\u015firleri", category: "bilardo" },
  { slug: "bilardo-uclari", name: "Bilardo U\u00e7lar\u0131", category: "bilardo" },
  { slug: "bilardo-cuhalari", name: "Bilardo \u00c7uhalar\u0131", category: "bilardo" },
  { slug: "istaka-cantalari", name: "Istaka \u00c7antalar\u0131", category: "bilardo" },
  { slug: "masa-lambalari", name: "Masa Lambalar\u0131", category: "bilardo" },
  { slug: "dart-urunleri", name: "Dart \u00dcr\u00fcnleri", category: "dart" },
  { slug: "kart-dagitici", name: "Kart Da\u011f\u0131t\u0131c\u0131", category: "oyun" },
  { slug: "langirt-urunleri", name: "Lang\u0131rt \u00dcr\u00fcnleri", category: "oyun" },
  { slug: "okey-urunleri", name: "Okey \u00dcr\u00fcnleri", category: "oyun" },
];

export const products: Product[] = [
  {
    id: "3881",
    slug: "nodleman-amerikan-bilardo-top-seti",
    name: "Nodleman Amerikan Bilardo Top Seti",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db00071_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Nodleman",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/nodleman-amerikan-bilardo-top-seti",
  },
  {
    id: "3879",
    slug: "king-ball-amerikan-bilardo-top-seti",
    name: "King Ball Amerikan Bilardo Top Seti",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db00069_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "King Ball",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/king-ball-amerikan-bilardo-top-seti",
  },
  {
    id: "3882",
    slug: "pool-balls-amerikan-bilardo-top-seti",
    name: "Pool Balls Amerikan Bilardo Top Seti",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db00072_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Pool Balls",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/pool-balls-amerikan-bilardo-top-seti",
  },
  {
    id: "4116",
    slug: "buffalo-pool-ball-set-54mm",
    name: "Buffalo Pool Ball Set 54mm",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db981458989311_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Buffalo",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/buffalo-pool-ball-set-54mm",
  },
  {
    id: "3886",
    slug: "aramith-pool-premium-top-seti-572-mm",
    name: "Aramith Pool Premium Top Seti 57.2 mm",
    price: 7643.42,
    image: "https://www.deryabilardo.com/img/products/small/db00086_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/aramith-pool-premium-top-seti-572-mm",
  },
  {
    id: "4262",
    slug: "billiard-balls-tournament-amerikan-top--uzakdogu-mense--",
    name: "Billiard Balls Tournament Amerikan Top-(uzakdo\u011fu men\u015fe )",
    price: 3184.71,
    image: "https://www.deryabilardo.com/img/products/small/poolcin0894913474_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/billiard-balls-tournament-amerikan-top--uzakdogu-mense--",
  },
  {
    id: "4114",
    slug: "aramith-premier-pool-ball-set-52-4-mm--2---1-16-inch-",
    name: "Aramith Premier POOL BALL SET 52,4 MM (2 - 1/16 INCH)",
    price: 7945.89,
    image: "https://www.deryabilardo.com/img/products/small/db9702472525003_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/aramith-premier-pool-ball-set-52-4-mm--2---1-16-inch-",
  },
  {
    id: "4113",
    slug: "aramith-premier-amerikan-bilardo-top-seti--508-mm-",
    name: "Aramith Premier Amerikan Bilardo Top Seti (50.8 mm)",
    price: 4352.23,
    image: "https://www.deryabilardo.com/img/products/small/db89327424002_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/aramith-premier-amerikan-bilardo-top-seti--508-mm-",
  },
  {
    id: "3878",
    slug: "yanmeia-amerikan-bilardo-top-seti",
    name: "Yanmeia Amerikan Bilardo Top Seti",
    price: 5307.85,
    image: "https://www.deryabilardo.com/img/products/small/db00066_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/yanmeia-amerikan-bilardo-top-seti",
  },
  {
    id: "3877",
    slug: "super-aramith-pro-cup-tv-profesyonel-pool-bilardo-top-seti--572-mm-",
    name: "Super Aramith Pro-Cup TV Profesyonel Pool Bilardo Top Seti (57.2 mm)",
    price: 11464.86,
    image: "https://www.deryabilardo.com/img/products/small/db00063_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/super-aramith-pro-cup-tv-profesyonel-pool-bilardo-top-seti--572-mm-",
  },
  {
    id: "3884",
    slug: "aramith-pool-procup-top-seti-572-mm",
    name: "Aramith Pool Procup Top Seti 57.2 mm",
    price: 10456.26,
    image: "https://www.deryabilardo.com/img/products/small/arampro00084_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/aramith-pool-procup-top-seti-572-mm",
  },
  {
    id: "5078",
    slug: "amerikan-top-magic",
    name: "Amerikan Top Magic",
    price: 518.58,
    image: "https://www.deryabilardo.com/img/products/small/38751ea4-f973-4ece-9a06-0745445346b2jpg-841f914.webp",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Magic",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/amerikan-top-magic",
  },
  {
    id: "3883",
    slug: "aramith-jim-rempe-ozel-bilardo-egitim-topu",
    name: "Aramith Jim Rempe \u00d6zel Bilardo E\u011fitim Topu",
    price: 2648.63,
    image: "https://www.deryabilardo.com/img/products/small/db00083_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "amerikan-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/amerikan-bilardo-toplari/aramith-jim-rempe-ozel-bilardo-egitim-topu",
  },
  {
    id: "4046",
    slug: "xin-kang-carom-4-top-seti",
    name: "Xin Kang Carom 4 Top Seti",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db0008932_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "3-bant-bilardo-toplari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/3-bant-bilardo-toplari/xin-kang-carom-4-top-seti",
  },
  {
    id: "4045",
    slug: "xin-kang-carom-3-top-seti",
    name: "Xin Kang Carom 3 Top Seti",
    price: 1592.36,
    image: "https://www.deryabilardo.com/img/products/small/db0005082_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "3-bant-bilardo-toplari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/3-bant-bilardo-toplari/xin-kang-carom-3-top-seti",
  },
  {
    id: "4112",
    slug: "super-aramith-traditional-3-bant-karambol-top-seti--615-mm-",
    name: "Super Aramith Traditional 3-Bant Karambol Top Seti (61.5 mm)",
    price: 3025.27,
    image: "https://www.deryabilardo.com/img/products/small/db04834377_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "3-bant-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/3-bant-bilardo-toplari/super-aramith-traditional-3-bant-karambol-top-seti--615-mm-",
  },
  {
    id: "3895",
    slug: "cosmos-diamond-ultra-c-profesyonel-bilardo-top-seti",
    name: "Cosmos Diamond Ultra-C Profesyonel Bilardo Top Seti",
    price: 12208.07,
    image: "https://www.deryabilardo.com/img/products/small/db00094_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "3-bant-bilardo-toplari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/3-bant-bilardo-toplari/cosmos-diamond-ultra-c-profesyonel-bilardo-top-seti",
  },
  {
    id: "4121",
    slug: "cyclop-zeus-tv-profesyonel-karambol-top-seti",
    name: "Cyclop Zeus TV Profesyonel Karambol Top Seti",
    price: 3450.11,
    image: "https://www.deryabilardo.com/img/products/small/db786908009_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "3-bant-bilardo-toplari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/3-bant-bilardo-toplari/cyclop-zeus-tv-profesyonel-karambol-top-seti",
  },
  {
    id: "4579",
    slug: "super-aramith-pro-cup-tek-top",
    name: "S\u00fcper Aramith Pro-Cup tek top",
    price: 1910.72,
    image: "https://www.deryabilardo.com/img/products/small/db00014_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "3-bant-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/3-bant-bilardo-toplari/super-aramith-pro-cup-tek-top",
  },
  {
    id: "4120",
    slug: "aramith-pro-cup-challenge-6-noktali-karambol-top-seti",
    name: "Aramith Pro-Cup Challenge 6 Noktal\u0131 Karambol Top Seti",
    price: 6687.79,
    image: "https://www.deryabilardo.com/img/products/small/db980009723534_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "3-bant-bilardo-toplari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/3-bant-bilardo-toplari/aramith-pro-cup-challenge-6-noktali-karambol-top-seti",
  },
  {
    id: "4044",
    slug: "predator-sanglee-rpl4",
    name: "Predator Sanglee RPL4",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db0006239_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Predator",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/predator-sanglee-rpl4",
  },
  {
    id: "4036",
    slug: "cuetec-rpl1",
    name: "Cuetec RPL1",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db0009889_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Cuetec",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/cuetec-rpl1",
  },
  {
    id: "4204",
    slug: "predator-ikon-2-rpl",
    name: "Predator Ikon-2 RPL",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db8776754-00988_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Predator",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/predator-ikon-2-rpl",
  },
  {
    id: "4037",
    slug: "cuetec-rpl2",
    name: "Cuetec RPL2",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db0008552_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Cuetec",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/cuetec-rpl2",
  },
  {
    id: "4041",
    slug: "meucci-rpl1",
    name: "meucci RPL1",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db0006236_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/meucci-rpl1",
  },
  {
    id: "4035",
    slug: "jacoby-rpl1",
    name: "Jacoby RPL1",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db002331_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/jacoby-rpl1",
  },
  {
    id: "4149",
    slug: "diamond-3-bant-istakasi",
    name: "Diamond 3 Bant Istakas\u0131",
    price: 2383.77,
    image: "https://www.deryabilardo.com/img/products/small/db832193030011_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/diamond-3-bant-istakasi",
  },
  {
    id: "4038",
    slug: "predator-icon-rpl2",
    name: "Predator Icon RPL2",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db0005129_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Predator",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/predator-icon-rpl2",
  },
  {
    id: "4479",
    slug: "cento-pba-blue-uc",
    name: "CENTO PBA BLUE U\u00c7",
    price: 849.15,
    image: "https://www.deryabilardo.com/img/products/small/db0707_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/cento-pba-blue-uc",
  },
  {
    id: "3860",
    slug: "kamui-clear-uc",
    name: "Kamui Clear U\u00e7",
    price: 1589.18,
    image: "https://www.deryabilardo.com/img/products/small/db00021_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/kamui-clear-uc",
  },
  {
    id: "4147",
    slug: "venus2-uc-bant-istakasi",
    name: "venus2 \u00fc\u00e7 bant \u0131stakas\u0131",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db9992521443267_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/venus2-uc-bant-istakasi",
  },
  {
    id: "4146",
    slug: "venus-3-bant-istakasi",
    name: "Ven\u00fcs 3 Bant Istakas\u0131",
    price: 2118.9,
    image: "https://www.deryabilardo.com/img/products/small/db837127662628999_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/venus-3-bant-istakasi",
  },
  {
    id: "4485",
    slug: "euroasya-ares-model-istaka",
    name: "EUROASYA ARES MODEL ISTAKA",
    price: 17515.92,
    image: "https://www.deryabilardo.com/img/products/small/db0904_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/euroasya-ares-model-istaka",
  },
  {
    id: "4040",
    slug: "mc-dermott-rpl2",
    name: "Mc Dermott RPL2",
    price: 3178.36,
    image: "https://www.deryabilardo.com/img/products/small/db0006235_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/mc-dermott-rpl2",
  },
  {
    id: "4503",
    slug: "longoni-nero-dip-ve-saft-kapagi",
    name: "LONGON\u0130 NERO D\u0130P VE \u015eAFT KAPA\u011eI",
    price: 690.23,
    image: "https://www.deryabilardo.com/img/products/small/db0987_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/longoni-nero-dip-ve-saft-kapagi",
  },
  {
    id: "3937",
    slug: "ds-latex-rubber-grip",
    name: "DS LATEX RUBBER GRIP",
    price: 1273.99,
    image: "https://www.deryabilardo.com/img/products/small/db0721_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/ds-latex-rubber-grip",
  },
  {
    id: "4083",
    slug: "britannia-england-profesyonel-snooker-bilardo-istakasi",
    name: "Britannia England Profesyonel Snooker Bilardo Istakas\u0131",
    price: 6369.43,
    image: "https://www.deryabilardo.com/img/products/small/britsnook45456031_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/britannia-england-profesyonel-snooker-bilardo-istakasi",
  },
  {
    id: "4103",
    slug: "buffalo-dominator-pool-cue",
    name: "Buffalo Dominator Pool Cue",
    price: 11942.67,
    image: "https://www.deryabilardo.com/img/products/small/dominator78784563_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Buffalo",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/buffalo-dominator-pool-cue",
  },
  {
    id: "4152",
    slug: "orijinal-cuetec2-fibercomp-rus-istakasi",
    name: "Orijinal Cuetec2 Fibercomp Rus Istakas\u0131",
    price: 5785.67,
    image: "https://www.deryabilardo.com/img/products/small/db81138301319_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/orijinal-cuetec2-fibercomp-rus-istakasi",
  },
  {
    id: "4480",
    slug: "cento-pba-black-uc",
    name: "CENTO PBA BLACK U\u00c7",
    price: 849.15,
    image: "https://www.deryabilardo.com/img/products/small/db0708_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/cento-pba-black-uc",
  },
  {
    id: "4156",
    slug: "orijinal-diamond-4-rus-istakasi",
    name: "Orijinal Diamond 4 Rus Istakas\u0131",
    price: 2919.32,
    image: "https://www.deryabilardo.com/img/products/small/db8328328240-3443_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/orijinal-diamond-4-rus-istakasi",
  },
  {
    id: "4169",
    slug: "longoni-amalia",
    name: "Longoni Amalia",
    price: 106157.09,
    image: "https://www.deryabilardo.com/img/products/small/dc726632555252001_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/longoni-amalia",
  },
  {
    id: "4089",
    slug: "molinari-novarossi-manticore-profesyonel-bilardo-istakasi",
    name: "Molinari NovaRossi Manticore Profesyonel Bilardo Istakas\u0131",
    price: 11146.49,
    image: "https://www.deryabilardo.com/img/products/small/db565643309_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/molinari-novarossi-manticore-profesyonel-bilardo-istakasi",
  },
  {
    id: "4090",
    slug: "molinari-novarossi-phoenix-profesyonel-bilardo-istakasi",
    name: "Molinari NovaRossi Phoenix Profesyonel Bilardo Istakas\u0131",
    price: 11146.49,
    image: "https://www.deryabilardo.com/img/products/small/db56067090_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-istakalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-istakalari/molinari-novarossi-phoenix-profesyonel-bilardo-istakasi",
  },
  {
    id: "4269",
    slug: "gold-star-920-bilardo-cuhasi-mavi--yesil",
    name: "Gold Star 920 Bilardo \u00c7uhas\u0131 Mavi -Ye\u015fil",
    price: 716.72,
    image: "https://www.deryabilardo.com/img/products/small/db989084138941-0490_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/gold-star-920-bilardo-cuhasi-mavi--yesil",
  },
  {
    id: "4270",
    slug: "gold-star-920-bilardo-cuhasi--yesil",
    name: "Gold Star 920 Bilardo \u00c7uhas\u0131  Ye\u015fil",
    price: 716.72,
    image: "https://www.deryabilardo.com/img/products/small/dbs7675645332222_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/gold-star-920-bilardo-cuhasi--yesil",
  },
  {
    id: "4272",
    slug: "prens-roll-cloth-blue",
    name: "Prens Roll Cloth Blue",
    price: 424.84,
    image: "https://www.deryabilardo.com/img/products/small/dbs7097930575_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/prens-roll-cloth-blue",
  },
  {
    id: "4031",
    slug: "gold-star-920-bilardo-cuhasi-g-green",
    name: "Gold Star 920 Bilardo \u00c7uhas\u0131 G-green",
    price: 716.72,
    image: "https://www.deryabilardo.com/img/products/small/db0006755_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/gold-star-920-bilardo-cuhasi-g-green",
  },
  {
    id: "4271",
    slug: "gold-star-920-bilardo-cuhasi-sari---yesil|",
    name: "Gold Star 920 Bilardo \u00c7uhas\u0131 Sar\u0131 - Ye\u015fil|",
    price: 716.72,
    image: "https://www.deryabilardo.com/img/products/small/dbs87867789*09-9*9_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/gold-star-920-bilardo-cuhasi-sari---yesil|",
  },
  {
    id: "4032",
    slug: "gold-star-920-blue-green-bilardo-cuhasi",
    name: "Gold Star 920 Blue Green Bilardo \u00c7uhas\u0131",
    price: 4750.58,
    image: "https://www.deryabilardo.com/img/products/small/db0008851_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/gold-star-920-blue-green-bilardo-cuhasi",
  },
  {
    id: "4030",
    slug: "gold-star-920-bilardo-cuhasi-yesil",
    name: "Gold Star 920 Bilardo \u00c7uhas\u0131 Ye\u015fil",
    price: 716.72,
    image: "https://www.deryabilardo.com/img/products/small/dbs0003455_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/gold-star-920-bilardo-cuhasi-yesil",
  },
  {
    id: "4029",
    slug: "gold-star-920-akrilik-bilardo-masasi-cuhasi-mavi",
    name: "Gold Star 920 Akrilik Bilardo Masas\u0131 \u00c7uhas\u0131 Mavi",
    price: 716.72,
    image: "https://www.deryabilardo.com/img/products/small/db0002324_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/gold-star-920-akrilik-bilardo-masasi-cuhasi-mavi",
  },
  {
    id: "4138",
    slug: "prens-epengle-150cm-enli-bilardo-cuhasi-yesil",
    name: "PRENS Epengle 150cm Enli Bilardo \u00c7uhas\u0131 YE\u015e\u0130L",
    price: 1486.41,
    image: "https://www.deryabilardo.com/img/products/small/db93823726525_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/prens-epengle-150cm-enli-bilardo-cuhasi-yesil",
  },
  {
    id: "4140",
    slug: "prens-180cm-enli-bilardo-cuhasi-yesil",
    name: "PRENS 180cm Enli Bilardo \u00c7uhas\u0131 YE\u015e\u0130L",
    price: 1486.41,
    image: "https://www.deryabilardo.com/img/products/small/db94937hhw4_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/prens-180cm-enli-bilardo-cuhasi-yesil",
  },
  {
    id: "4128",
    slug: "golden-horn-3-bant-cuhasi--takim-",
    name: "Golden Horn 3 Bant \u00c7uhas\u0131 (Tak\u0131m)",
    price: 4352.23,
    image: "https://www.deryabilardo.com/img/products/small/db0009282725003_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/golden-horn-3-bant-cuhasi--takim-",
  },
  {
    id: "4139",
    slug: "prens-epengle-180cm-enli-bilardo-cuhasi-mavi",
    name: "PRENS Epengle 180cm Enli Bilardo \u00c7uhas\u0131 MAV\u0130",
    price: 2118.9,
    image: "https://www.deryabilardo.com/img/products/small/db09993jhg776_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/prens-epengle-180cm-enli-bilardo-cuhasi-mavi",
  },
  {
    id: "4137",
    slug: "prens-epengle-150cm-enli-bilardo-cuhasi-mavi",
    name: "PRENS Epengle 150cm Enli Bilardo \u00c7uhas\u0131 MAV\u0130",
    price: 1486.41,
    image: "https://www.deryabilardo.com/img/products/small/db90388438373_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/prens-epengle-150cm-enli-bilardo-cuhasi-mavi",
  },
  {
    id: "4129",
    slug: "promatch-federasyon-cuhasi",
    name: "ProMatch Federasyon \u00c7uhas\u0131",
    price: 3520.56,
    image: "https://www.deryabilardo.com/img/products/small/db7772990209_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/promatch-federasyon-cuhasi",
  },
  {
    id: "4130",
    slug: "iwan-simonis-rapid300-delsa-blue-set",
    name: "Iwan Simonis Rapid300 Delsa Blue Set",
    price: 19108.28,
    image: "https://www.deryabilardo.com/img/products/small/db73761660011_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-cuhalari",
    brand: "Iwan Simonis",
    sourceUrl: "https://www.deryabilardo.com/bilardo-cuhalari/iwan-simonis-rapid300-delsa-blue-set",
  },
  {
    id: "3940",
    slug: "amerikan-masa-kose-lastik-seti",
    name: "Amerikan Masa K\u00f6\u015fe Lastik Seti",
    price: 318.37,
    image: "https://www.deryabilardo.com/img/products/small/db00338_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/amerikan-masa-kose-lastik-seti",
  },
  {
    id: "3941",
    slug: "amerikan-vurus-noktasi-sticker-10-lu-pakette-",
    name: "Amerikan Vuru\u015f Noktas\u0131 Sticker(10 lu pakette)",
    price: 265.39,
    image: "https://www.deryabilardo.com/img/products/small/db00391_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/amerikan-vurus-noktasi-sticker-10-lu-pakette-",
  },
  {
    id: "4124",
    slug: "gorina-no-press",
    name: "Gorina No-Press",
    price: 1061.57,
    image: "https://www.deryabilardo.com/img/products/small/db7899900000876009_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Gorina",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/gorina-no-press",
  },
  {
    id: "3936",
    slug: "longoni-fiber-jbr",
    name: "Longoni Fiber JBR",
    price: 477.81,
    image: "https://www.deryabilardo.com/img/products/small/db00333_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/longoni-fiber-jbr",
  },
  {
    id: "3953",
    slug: "buffalo-bumper",
    name: "Buffalo Bumper",
    price: 371.34,
    image: "https://www.deryabilardo.com/img/products/small/db00403_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Buffalo",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/buffalo-bumper",
  },
  {
    id: "3954",
    slug: "aramith-profesyonel-bilardo-topu-onarici-ve-parlatici-solusyon",
    name: "Aramith Profesyonel Bilardo Topu Onar\u0131c\u0131 ve Parlat\u0131c\u0131 Sol\u00fcsyon",
    price: 743.21,
    image: "https://www.deryabilardo.com/img/products/small/db00405_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/aramith-profesyonel-bilardo-topu-onarici-ve-parlatici-solusyon",
  },
  {
    id: "4275",
    slug: "ibs-supergrip",
    name: "IBS SUPERGRIP",
    price: 1112.42,
    image: "https://www.deryabilardo.com/img/products/small/dbs09234083247_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/ibs-supergrip",
  },
  {
    id: "3943",
    slug: "rato-buffalo",
    name: "Rato Buffalo",
    price: 398.35,
    image: "https://www.deryabilardo.com/img/products/small/db00396_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Buffalo",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/rato-buffalo",
  },
  {
    id: "3939",
    slug: "uc-iskencesi",
    name: "U\u00e7 \u0130\u015fkencesi",
    price: 201.83,
    image: "https://www.deryabilardo.com/img/products/small/db00336_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/uc-iskencesi",
  },
  {
    id: "3955",
    slug: "aramith-fenolik-bilardo-topu-temizleyici",
    name: "Aramith Fenolik Bilardo Topu Temizleyici",
    price: 796.18,
    image: "https://www.deryabilardo.com/img/products/small/db00410_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Aramith",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/aramith-fenolik-bilardo-topu-temizleyici",
  },
  {
    id: "4878",
    slug: "bossa-super-gold-epengle-kumas",
    name: "BOSSA SUPER GOLD EPENGLE KUMA\u015e",
    price: 1937.21,
    image: "https://www.deryabilardo.com/img/products/small/db901_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/bossa-super-gold-epengle-kumas",
  },
  {
    id: "4162",
    slug: "bilardo-top-silme-makinasi",
    name: "Bilardo Top Silme Makinas\u0131",
    price: 13269.64,
    image: "https://www.deryabilardo.com/img/products/small/topsilmmak928276561-2_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/bilardo-top-silme-makinasi",
  },
  {
    id: "4533",
    slug: "sprey-bilardo-top-temizleyicisi",
    name: "SPREY B\u0130LARDO TOP TEM\u0130ZLEY\u0130C\u0130S\u0130",
    price: 796.18,
    image: "https://www.deryabilardo.com/img/products/small/db000000_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/sprey-bilardo-top-temizleyicisi",
  },
  {
    id: "4122",
    slug: "snooker-masa-kancasi",
    name: "Snooker Masa Kancas\u0131",
    price: 636.73,
    image: "https://www.deryabilardo.com/img/products/small/db938726255003_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/snooker-masa-kancasi",
  },
  {
    id: "4057",
    slug: "cuetec-tip-shaper-tuylendirici",
    name: "Cuetec Tip Shaper-t\u00fcylendirici",
    price: 955.63,
    image: "https://www.deryabilardo.com/img/products/small/cuetip3675_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Cuetec",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/cuetec-tip-shaper-tuylendirici",
  },
  {
    id: "4277",
    slug: "longoni-razor-carbon-bicakli-kalemtras",
    name: "Longoni Razor Carbon B\u0131\u00e7akl\u0131 Kalemtra\u015f",
    price: 1061.57,
    image: "https://www.deryabilardo.com/img/products/small/dbs98477735787755_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/longoni-razor-carbon-bicakli-kalemtras",
  },
  {
    id: "3938",
    slug: "bilardo-kul-tablasi",
    name: "Bilardo K\u00fcl Tablas\u0131",
    price: 902.12,
    image: "https://www.deryabilardo.com/img/products/small/db00335_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/bilardo-kul-tablasi",
  },
  {
    id: "4065",
    slug: "minyatur-bilardo-evi",
    name: "Minyat\u00fcr Bilardo Evi",
    price: 2123.14,
    image: "https://www.deryabilardo.com/img/products/small/db20909087012_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-aksesuarlari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-aksesuarlari/minyatur-bilardo-evi",
  },
  {
    id: "4495",
    slug: "billking-eldiven-cutting-seson---red",
    name: "BILLKING ELD\u0130VEN Cutting Seson - Red",
    price: 690.23,
    image: "https://www.deryabilardo.com/img/products/small/db0913_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-eldivenleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-eldivenleri/billking-eldiven-cutting-seson---red",
  },
  {
    id: "3935",
    slug: "longoni-eldiven-sultan",
    name: "Longoni Eldiven Sultan",
    price: 1592.36,
    image: "https://www.deryabilardo.com/img/products/small/db00319_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-eldivenleri",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/bilardo-eldivenleri/longoni-eldiven-sultan",
  },
  {
    id: "4489",
    slug: "predator-eldiven-siyah-gold",
    name: "Predator Eldiven siyah gold",
    price: 3184.71,
    image: "https://www.deryabilardo.com/img/products/small/db0908_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-eldivenleri",
    brand: "Predator",
    sourceUrl: "https://www.deryabilardo.com/bilardo-eldivenleri/predator-eldiven-siyah-gold",
  },
  {
    id: "4175",
    slug: "longoni-sultan-20-billiard-pool-cue-glove",
    name: "Longoni Sultan 2.0 Billiard Pool Cue Glove",
    price: 2123.14,
    image: "https://www.deryabilardo.com/img/products/small/db0718_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-eldivenleri",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/bilardo-eldivenleri/longoni-sultan-20-billiard-pool-cue-glove",
  },
  {
    id: "4237",
    slug: "ball-teck-premium-bilardo-tebesiri",
    name: "Ball-Teck Premium Bilardo Tebe\u015firi",
    price: 1167.52,
    image: "https://www.deryabilardo.com/img/products/small/balltekchalk9976655421212_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/ball-teck-premium-bilardo-tebesiri",
  },
  {
    id: "4235",
    slug: "gorina-premium-bilardo-tebesiri-2-li-paket",
    name: "Gorina Premium Bilardo Tebe\u015firi 2\u2019li Paket",
    price: 1035.08,
    image: "https://www.deryabilardo.com/img/products/small/gorinachalk097896754543_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Gorina",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/gorina-premium-bilardo-tebesiri-2-li-paket",
  },
  {
    id: "3929",
    slug: "predator-tebesir-5-li",
    name: "Predator Tebe\u015fir 5\u2019li",
    price: 796.18,
    image: "https://www.deryabilardo.com/img/products/small/db00221_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Predator",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/predator-tebesir-5-li",
  },
  {
    id: "3923",
    slug: "longoni-tebesir-blue-diamond",
    name: "Longoni Tebe\u015fir Blue Diamond",
    price: 690.23,
    image: "https://www.deryabilardo.com/img/products/small/db00212_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/longoni-tebesir-blue-diamond",
  },
  {
    id: "3930",
    slug: "taom-tebesir",
    name: "Taom Tebe\u015fir",
    price: 1326.96,
    image: "https://www.deryabilardo.com/img/products/small/db00219_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/taom-tebesir",
  },
  {
    id: "4263",
    slug: "gorina-ultra-lux-tebesir-metal-kutu-2-li",
    name: "Gorina Ultra Lux Tebe\u015fir Metal Kutu 2\u2019li",
    price: 1698.3,
    image: "https://www.deryabilardo.com/img/products/small/gorinaikilichlkmet9740374090004_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Gorina",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/gorina-ultra-lux-tebesir-metal-kutu-2-li",
  },
  {
    id: "3924",
    slug: "master-tebesir-kirmizi-12-li",
    name: "Master Tebe\u015fir K\u0131rm\u0131z\u0131 12\u2019li",
    price: 477.81,
    image: "https://www.deryabilardo.com/img/products/small/db00214_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Master",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/master-tebesir-kirmizi-12-li",
  },
  {
    id: "3922",
    slug: "kamui-roku-tebesir---mavi",
    name: "Kamui Roku Tebe\u015fir - Mavi",
    price: 1698.3,
    image: "https://www.deryabilardo.com/img/products/small/db00211_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/kamui-roku-tebesir---mavi",
  },
  {
    id: "3926",
    slug: "master-tebesir-yesil-12-li",
    name: "Master Tebe\u015fir Ye\u015fil 12\u2019li",
    price: 477.81,
    image: "https://www.deryabilardo.com/img/products/small/db00213_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Master",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/master-tebesir-yesil-12-li",
  },
  {
    id: "3928",
    slug: "master-tebesir-kahverengi-12-li",
    name: "Master Tebe\u015fir Kahverengi 12\u2019li",
    price: 477.81,
    image: "https://www.deryabilardo.com/img/products/small/db00220_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Master",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/master-tebesir-kahverengi-12-li",
  },
  {
    id: "3925",
    slug: "master-tebesir-mavi-12-li",
    name: "Master Tebe\u015fir Mavi 12\u2019li",
    price: 690.23,
    image: "https://www.deryabilardo.com/img/products/small/db00215_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-tebesirleri",
    brand: "Master",
    sourceUrl: "https://www.deryabilardo.com/bilardo-tebesirleri/master-tebesir-mavi-12-li",
  },
  {
    id: "3962",
    slug: "triangle-uc-50-li-paket",
    name: "Triangle U\u00e7 50\u2019li Paket",
    price: 2759.87,
    image: "https://www.deryabilardo.com/img/products/small/db000601_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/triangle-uc-50-li-paket",
  },
  {
    id: "3966",
    slug: "master-uc-50-lik-paket",
    name: "Master U\u00e7 50\u2019lik Paket",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db000788_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: "Master",
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/master-uc-50-lik-paket",
  },
  {
    id: "4488",
    slug: "m-sasaki-bilardo-istaka-ucu",
    name: "M Sasaki Bilardo Istaka Ucu",
    price: 212.42,
    image: "https://www.deryabilardo.com/img/products/small/db0907_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/m-sasaki-bilardo-istaka-ucu",
  },
  {
    id: "4238",
    slug: "chao-black-uc--original-korea-",
    name: "Chao Black U\u00e7 (Original Korea)",
    price: 175.34,
    image: "https://www.deryabilardo.com/img/products/small/db88657445332_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/chao-black-uc--original-korea-",
  },
  {
    id: "4483",
    slug: "euroasya-helen-model-istaka",
    name: "EUROASYA HELEN MODEL ISTAKA",
    price: 17515.92,
    image: "https://www.deryabilardo.com/img/products/small/db0901_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/euroasya-helen-model-istaka",
  },
  {
    id: "4484",
    slug: "euroasya-poison-model-istaka",
    name: "EUROASYA POISON MODEL ISTAKA",
    price: 17515.92,
    image: "https://www.deryabilardo.com/img/products/small/db0902_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/euroasya-poison-model-istaka",
  },
  {
    id: "4239",
    slug: "ibs-uc--original-korea-",
    name: "IBS U\u00e7 (Original Korea)",
    price: 132.96,
    image: "https://www.deryabilardo.com/img/products/small/ibsuc989076635323223_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/ibs-uc--original-korea-",
  },
  {
    id: "3862",
    slug: "aura-uc",
    name: "Aura U\u00e7",
    price: 1273.99,
    image: "https://www.deryabilardo.com/img/products/small/db00024_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/aura-uc",
  },
  {
    id: "4487",
    slug: "kimchi-tip-2ea-case-billiards-10layer-m-q-carom-3-cusion-expert-player",
    name: "KIMCHI Tip 2ea+Case Billiards 10layer M Q Carom 3 Cusion Expert Player",
    price: 1221.02,
    image: "https://www.deryabilardo.com/img/products/small/db0906_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/kimchi-tip-2ea-case-billiards-10layer-m-q-carom-3-cusion-expert-player",
  },
  {
    id: "4492",
    slug: "zest-istaka-ucu",
    name: "ZEST ISTAKA UCU",
    price: 690.23,
    image: "https://www.deryabilardo.com/img/products/small/db0911_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/zest-istaka-ucu",
  },
  {
    id: "4493",
    slug: "billking-cl-kahverengi-mh-uc",
    name: "BILLKING CL KAHVERENG\u0130 MH U\u00c7",
    price: 371.34,
    image: "https://www.deryabilardo.com/img/products/small/db09011_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/billking-cl-kahverengi-mh-uc",
  },
  {
    id: "4497",
    slug: "kamui-athlete-uc",
    name: "KAMUI ATHLETE U\u00c7",
    price: 1589.18,
    image: "https://www.deryabilardo.com/img/products/small/db0915_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/kamui-athlete-uc",
  },
  {
    id: "4265",
    slug: "billking-pro-tip-maker",
    name: "Billking Pro Tip Maker",
    price: 4405.73,
    image: "https://www.deryabilardo.com/img/products/small/billkingtamir789675439897_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/billking-pro-tip-maker",
  },
  {
    id: "4266",
    slug: "gorina-celik-zimpara",
    name: "Gorina \u00c7elik Z\u0131mpara",
    price: 1432.91,
    image: "https://www.deryabilardo.com/img/products/small/dbs78967543322_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "bilardo-uclari",
    brand: "Gorina",
    sourceUrl: "https://www.deryabilardo.com/bilardo-uclari/gorina-celik-zimpara",
  },
  {
    id: "4056",
    slug: "cuetec-cue-case",
    name: "Cuetec Cue Case",
    price: 1592.36,
    image: "https://www.deryabilardo.com/img/products/small/istcantasi20090908_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "istaka-cantalari",
    brand: "Cuetec",
    sourceUrl: "https://www.deryabilardo.com/istaka-cantalari/cuetec-cue-case",
  },
  {
    id: "4285",
    slug: "buffalo-eko-canta",
    name: "BUFFALO EKO \u00c7ANTA",
    price: 690.23,
    image: "https://www.deryabilardo.com/img/products/small/dbs8775544309_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "istaka-cantalari",
    brand: "Buffalo",
    sourceUrl: "https://www.deryabilardo.com/istaka-cantalari/buffalo-eko-canta",
  },
  {
    id: "4102",
    slug: "mass-hard-case-istaka-cantasi",
    name: "Mass Hard Case Istaka \u00c7antas\u0131",
    price: 4511.68,
    image: "https://www.deryabilardo.com/img/products/small/db344261661_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "istaka-cantalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/istaka-cantalari/mass-hard-case-istaka-cantasi",
  },
  {
    id: "3984",
    slug: "laperti-eco-canta",
    name: "Laperti Eco \u00c7anta",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/db000445_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "istaka-cantalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/istaka-cantalari/laperti-eco-canta",
  },
  {
    id: "4084",
    slug: "snooker-bilardo-istaka-cantasi",
    name: "Snooker Bilardo Istaka \u00c7antas\u0131",
    price: 1857.75,
    image: "https://www.deryabilardo.com/img/products/small/dbcasa34012200655_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "istaka-cantalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/istaka-cantalari/snooker-bilardo-istaka-cantasi",
  },
  {
    id: "4085",
    slug: "snooker-istaka-cantasi-3-4",
    name: "Snooker Istaka \u00c7antas\u0131 3/4",
    price: 1592.36,
    image: "https://www.deryabilardo.com/img/products/small/db5500235001_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "istaka-cantalari",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/istaka-cantalari/snooker-istaka-cantasi-3-4",
  },
  {
    id: "4938",
    slug: "longoni-giotto-autunno-4x8-luks-istaka-cantasi",
    name: "Longoni Giotto Autunno Deri Istaka \u00c7antas\u0131 4x8 | L\u00fcks Bilardo Aksesuarlar\u0131",
    price: 38670.0,
    image: "https://www.deryabilardo.com/img/products/small/gi\u0307ottor-800x800-ef7c2a3.webp",
    category: "bilardo",
    subcategorySlug: "istaka-cantalari",
    brand: "Longoni",
    sourceUrl: "https://www.deryabilardo.com/istaka-cantalari/longoni-giotto-autunno-4x8-luks-istaka-cantasi",
  },
  {
    id: "4067",
    slug: "longfield-steel-dart-3-lu-set",
    name: "LONGFIELD Steel Dart 3\u2019l\u00fc Set",
    price: 716.72,
    image: "https://www.deryabilardo.com/img/products/small/db7770874_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/longfield-steel-dart-3-lu-set",
  },
  {
    id: "4876",
    slug: "spare-rings",
    name: "Spare Rings",
    price: 63.57,
    image: "https://www.deryabilardo.com/img/products/small/dbsparer_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/spare-rings",
  },
  {
    id: "3905",
    slug: "winmau-broadside-pirinc-celik-uclu-dart-oku",
    name: "Winmau Broadside Pirin\u00e7 \u00c7elik U\u00e7lu Dart Oku",
    price: 1061.57,
    image: "https://www.deryabilardo.com/img/products/small/db00128_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-broadside-pirinc-celik-uclu-dart-oku",
  },
  {
    id: "3932",
    slug: "winmau-pro-sfb-dart-tahtasi",
    name: "Winmau Pro SFB Dart Tahtas\u0131",
    price: 3980.89,
    image: "https://www.deryabilardo.com/img/products/small/db00302_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-pro-sfb-dart-tahtasi",
  },
  {
    id: "4063",
    slug: "winmau-blade-6-profesyonel-dart-tahtasi",
    name: "Winmau Blade 6 Profesyonel Dart Tahtas\u0131",
    price: 5323.75,
    image: "https://www.deryabilardo.com/img/products/small/winmblade6_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-blade-6-profesyonel-dart-tahtasi",
  },
  {
    id: "4286",
    slug: "winmau-neutron-steel-dart-oku",
    name: "Winmau Neutron Steel Dart Oku",
    price: 796.18,
    image: "https://www.deryabilardo.com/img/products/small/dbs*9*4934_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-neutron-steel-dart-oku",
  },
  {
    id: "4069",
    slug: "winmau-deluxe-pirinc-dart-hediye-seti",
    name: "Winmau Deluxe Pirin\u00e7 Dart Hediye Seti",
    price: 1167.52,
    image: "https://www.deryabilardo.com/img/products/small/db90908706001_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-deluxe-pirinc-dart-hediye-seti",
  },
  {
    id: "4573",
    slug: "xq-max-originals-world-champion-90yuzde-tungsten-dart-seti",
    name: "XQ Max Originals World Champion 90% Tungsten Dart Seti",
    price: 2335.56,
    image: "https://www.deryabilardo.com/img/products/small/db0010_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/xq-max-originals-world-champion-90yuzde-tungsten-dart-seti",
  },
  {
    id: "4506",
    slug: "harrows-set-of-3-flights",
    name: "HARROWS SET OF 3 FLIGHTS",
    price: 105.95,
    image: "https://www.deryabilardo.com/img/products/small/db0740_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-set-of-3-flights",
  },
  {
    id: "3901",
    slug: "master-dart-eko",
    name: "Master Dart Eko",
    price: 636.73,
    image: "https://www.deryabilardo.com/img/products/small/db00113_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Master",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/master-dart-eko",
  },
  {
    id: "4107",
    slug: "winmau-blade-6-dual-core-profesyonel-dart-tahtasi",
    name: "Winmau Blade 6 Dual-Core Profesyonel Dart Tahtas\u0131",
    price: 6436.17,
    image: "https://www.deryabilardo.com/img/products/small/db0574_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-blade-6-dual-core-profesyonel-dart-tahtasi",
  },
  {
    id: "4439",
    slug: "winmau-danny-noppert-90yuzde-tungsten-23g-celik-uclu-dart-oku",
    name: "Winmau Danny Noppert 90% Tungsten 23g \u00c7elik U\u00e7lu Dart Oku",
    price: 4343.75,
    image: "https://www.deryabilardo.com/img/products/small/db0531_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-danny-noppert-90yuzde-tungsten-23g-celik-uclu-dart-oku",
  },
  {
    id: "3903",
    slug: "winmau-dart-neutron",
    name: "Winmau Dart Neutron",
    price: 796.18,
    image: "https://www.deryabilardo.com/img/products/small/db00115_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-dart-neutron",
  },
  {
    id: "4860",
    slug: "harrows-vortex-flight",
    name: "Harrows Vortex Flight",
    price: 37.08,
    image: "https://www.deryabilardo.com/img/products/small/dbvortex_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-vortex-flight",
  },
  {
    id: "4854",
    slug: "harrows-paragon-flight",
    name: "Harrows Paragon Flight",
    price: 42.38,
    image: "https://www.deryabilardo.com/img/products/small/dbparagon_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-paragon-flight",
  },
  {
    id: "3900",
    slug: "harrows-super-pro-dart-ayarlama-seti",
    name: "Harrows Super Pro Dart Ayarlama Seti",
    price: 955.63,
    image: "https://www.deryabilardo.com/img/products/small/db00112_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-super-pro-dart-ayarlama-seti",
  },
  {
    id: "5107",
    slug: "winmau-blackout-yuzde90-tungsten-dart-oku",
    name: "Winmau Blackout 90% Tungsten Dart Oku",
    price: 3337.27,
    image: "https://www.deryabilardo.com/img/products/small/10832022g20blackout20-20image201-18be3d4.webp",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-blackout-yuzde90-tungsten-dart-oku",
  },
  {
    id: "4870",
    slug: "harrows-smart-dart-cantasi",
    name: "Harrows Smart Dart \u00c7antas\u0131",
    price: 743.21,
    image: "https://www.deryabilardo.com/img/products/small/dbsmartcase_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-smart-dart-cantasi",
  },
  {
    id: "4846",
    slug: "harrows-dimplex-s3-flight",
    name: "Harrows Dimplex S3 Flight",
    price: 37.08,
    image: "https://www.deryabilardo.com/img/products/small/dbdimplexs3_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-dimplex-s3-flight",
  },
  {
    id: "4843",
    slug: "harrows-retina-dart-flight",
    name: "Harrows Retina Dart Flight",
    price: 42.38,
    image: "https://www.deryabilardo.com/img/products/small/dbretina_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-retina-dart-flight",
  },
  {
    id: "4034",
    slug: "winmau-surraunds",
    name: "Winmau Surraunds",
    price: 3178.36,
    image: "https://www.deryabilardo.com/img/products/small/db0006774_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-surraunds",
  },
  {
    id: "4852",
    slug: "harrows-tessera-flight",
    name: "Harrows Tessera Flight",
    price: 42.38,
    image: "https://www.deryabilardo.com/img/products/small/dbtessera_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-tessera-flight",
  },
  {
    id: "4438",
    slug: "winmau-firestorm-flame-yuzde90-tungsten",
    name: "WINMAU FIRESTORM FLAME %90 TUNGSTEN",
    price: 4726.22,
    image: "https://www.deryabilardo.com/img/products/small/db0530_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Winmau",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/winmau-firestorm-flame-yuzde90-tungsten",
  },
  {
    id: "4872",
    slug: "harrows-blaze-fire-pro-3-dart-cantasi",
    name: "Harrows Blaze Fire Pro 3 Dart \u00c7antas\u0131",
    price: 690.23,
    image: "https://www.deryabilardo.com/img/products/small/dbblazepro3_td_3.jpg",
    category: "dart",
    subcategorySlug: "dart-urunleri",
    brand: "Harrows",
    sourceUrl: "https://www.deryabilardo.com/dart-urunleri/harrows-blaze-fire-pro-3-dart-cantasi",
  },
  {
    id: "4234",
    slug: "domino-buyuk-boy-ahsap-kutulu",
    name: "Domino B\u00fcy\u00fck Boy Ah\u015fap Kutulu",
    price: 902.12,
    image: "https://www.deryabilardo.com/img/products/small/db86755445357_td_3.jpg",
    category: "oyun",
    subcategorySlug: "okey-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/okey-urunleri/domino-buyuk-boy-ahsap-kutulu",
  },
  {
    id: "4528",
    slug: "sedef-kakmali-oval-oymali-masif-ahsap-okey-takimi",
    name: "Sedef Kakmal\u0131 Oval Oymal\u0131 Masif Ah\u015fap Okey Tak\u0131m\u0131",
    price: 17462.95,
    image: "https://www.deryabilardo.com/img/products/small/db00999_td_3.jpg",
    category: "oyun",
    subcategorySlug: "okey-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/okey-urunleri/sedef-kakmali-oval-oymali-masif-ahsap-okey-takimi",
  },
  {
    id: "4236",
    slug: "star-agac-oval-okey-takimi",
    name: "Star A\u011fa\u00e7 Oval Okey Tak\u0131m\u0131",
    price: 4138.22,
    image: "https://www.deryabilardo.com/img/products/small/db9873712334441_td_3.jpg",
    category: "oyun",
    subcategorySlug: "okey-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/okey-urunleri/star-agac-oval-okey-takimi",
  },
  {
    id: "3975",
    slug: "bogazici-cafe-rainbow-okey-takimi",
    name: "Bo\u011fazi\u00e7i Cafe Rainbow Okey Tak\u0131m\u0131",
    price: 2759.87,
    image: "https://www.deryabilardo.com/img/products/small/ovalokeyrenkli000902_td_3.jpg",
    category: "oyun",
    subcategorySlug: "okey-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/okey-urunleri/bogazici-cafe-rainbow-okey-takimi",
  },
  {
    id: "3976",
    slug: "bogazici-aspendos-dark-exclusive-okey",
    name: "Bo\u011fazi\u00e7i Aspendos Dark Exclusive Okey",
    price: 4671.12,
    image: "https://www.deryabilardo.com/img/products/small/ovalokey000888_td_3.jpg",
    category: "oyun",
    subcategorySlug: "okey-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/okey-urunleri/bogazici-aspendos-dark-exclusive-okey",
  },
  {
    id: "4171",
    slug: "bison-langirt",
    name: "Bison Lang\u0131rt",
    price: 31847.13,
    image: "https://www.deryabilardo.com/img/products/small/bisonlang828272651_td_3.jpg",
    category: "oyun",
    subcategorySlug: "langirt-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/langirt-urunleri/bison-langirt",
  },
  {
    id: "4535",
    slug: "4ft-mdf-langirt-masasi",
    name: "4FT MDF LANGIRT MASASI",
    price: 9023.35,
    image: "https://www.deryabilardo.com/img/products/small/db00009_td_3.jpg",
    category: "oyun",
    subcategorySlug: "langirt-urunleri",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/langirt-urunleri/4ft-mdf-langirt-masasi",
  },
  {
    id: "3866",
    slug: "garlando-f-200-evolution-langirt-masasi",
    name: "Garlando F-200 Evolution Lang\u0131rt Masas\u0131",
    price: 45116.76,
    image: "https://www.deryabilardo.com/img/products/small/db00035_td_3.jpg",
    category: "oyun",
    subcategorySlug: "langirt-urunleri",
    brand: "Garlando",
    sourceUrl: "https://www.deryabilardo.com/langirt-urunleri/garlando-f-200-evolution-langirt-masasi",
  },
  {
    id: "3867",
    slug: "roberto-sport-champion-six-langirt-masasi--6-oyuncu-",
    name: "Roberto Sport Champion Six Lang\u0131rt Masas\u0131 (6 Oyuncu)",
    price: 42462.84,
    image: "https://www.deryabilardo.com/img/products/small/db00037_td_3.jpg",
    category: "oyun",
    subcategorySlug: "langirt-urunleri",
    brand: "Roberto Sport",
    sourceUrl: "https://www.deryabilardo.com/langirt-urunleri/roberto-sport-champion-six-langirt-masasi--6-oyuncu-",
  },
  {
    id: "3868",
    slug: "roberto-sport-college-langirt-masasi",
    name: "Roberto Sport College Lang\u0131rt Masas\u0131",
    price: 36624.2,
    image: "https://www.deryabilardo.com/img/products/small/db00036_td_3.jpg",
    category: "oyun",
    subcategorySlug: "langirt-urunleri",
    brand: "Roberto Sport",
    sourceUrl: "https://www.deryabilardo.com/langirt-urunleri/roberto-sport-college-langirt-masasi",
  },
  {
    id: "3863",
    slug: "garlando-f-200-akcaagac-langirt-masasi",
    name: "Garlando F-200 Ak\u00e7aa\u011fa\u00e7 Lang\u0131rt Masas\u0131",
    price: 45116.76,
    image: "https://www.deryabilardo.com/img/products/small/db00028_td_3.jpg",
    category: "oyun",
    subcategorySlug: "langirt-urunleri",
    brand: "Garlando",
    sourceUrl: "https://www.deryabilardo.com/langirt-urunleri/garlando-f-200-akcaagac-langirt-masasi",
  },
  {
    id: "4059",
    slug: "buffalo-masa-lambasi-4lu",
    name: "Buffalo Masa Lambas\u0131 4l\u00fc",
    price: 5998.09,
    image: "https://www.deryabilardo.com/img/products/small/lamba0908970_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "masa-lambalari",
    brand: "Buffalo",
    sourceUrl: "https://www.deryabilardo.com/masa-lambalari/buffalo-masa-lambasi-4lu",
  },
  {
    id: "4058",
    slug: "buffalo-masa-lambasi-3lu",
    name: "Buffalo Masa Lambas\u0131 3l\u00fc",
    price: 5732.69,
    image: "https://www.deryabilardo.com/img/products/small/dbs989901_td_3.jpg",
    category: "bilardo",
    subcategorySlug: "masa-lambalari",
    brand: "Buffalo",
    sourceUrl: "https://www.deryabilardo.com/masa-lambalari/buffalo-masa-lambasi-3lu",
  },
  {
    id: "4172",
    slug: "black-jack-kart-dagitici",
    name: "Black Jack Kart Da\u011f\u0131t\u0131c\u0131",
    price: 1432.91,
    image: "https://www.deryabilardo.com/img/products/small/cardshoe635344-2_td_3.jpg",
    category: "oyun",
    subcategorySlug: "kart-dagitici",
    brand: null,
    sourceUrl: "https://www.deryabilardo.com/kart-dagitici/black-jack-kart-dagitici",
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('tr-TR', {
    style: 'currency',
    currency: 'TRY',
    minimumFractionDigits: 2,
  }).format(price);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category);
}

export function getProductsBySubcategory(subcategorySlug: string): Product[] {
  return products.filter((p) => p.subcategorySlug === subcategorySlug);
}

export function getSubcategoriesByCategory(category: Category): Subcategory[] {
  return subcategories.filter((s) => s.category === category);
}

export function getFeaturedProducts(count = 8): Product[] {
  return [...products].sort((a, b) => b.price - a.price).slice(0, count);
}
